version: '3'
services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "passw@rd"
      MYSQL_DATABASE: "spin"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql/data:/var/lib/mysql

  backend:
    build: ./conf/backend
    tty: true
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
    ports:
      - "8080:80"
    privileged: true
    depends_on:
      - db

  frontend:
    build: ./conf/frontend
    tty: true
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  node_modules:
  vendor: