openapi: "3.0.0"
info:
  title: "Spin API"
  description: "Spin Backend Service API"
  version: "1.0.0"
paths:
  /api/register:
    $ref: "api.register.yaml"
  /api/login:
    $ref: "api.login.yaml"
  /api/logout:
    $ref: "api.logout.yaml"
  /api/forgot_password:
    $ref: "api.forgot_password.yaml"
  /api/reset_password:
    $ref: "api.reset_password.yaml"
  /api/v1/information:
    $ref: "api.v1.information.yaml"
  /api/v1/information/{id}:
    $ref: "api.v1.information.show.yaml"

components:
  # Bearer認証
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
